version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: pimientadb
      POSTGRES_USER: pimienta
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pimienta@mail.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - 5050:80

volumes:
  postgres_data: {}
