version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=pimientadb
      - POSTGRES_USER=pimienta
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pimienta@mail.com
      - PGADMIN_DEFAULT_PASSWORD=pass
    ports:
      - 5050:80

  # mysql:
  #   image: mysql:5
  #   environment:
  #     - MYSQL_DATABASE=pimientadb
  #     - MYSQL_USER=pimienta
  #     - MYSQL_ROOT_PASSWORD=pass
  #     - MYSQL_PORT=3306
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql
